server:
  port: 6754
spring:
  application:
    name: cloud-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true  #feign.hystrix.enabled : 是否开启熔断器
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'
    context-path: /