server:
  port: 9862

spring:
  application:
    name: cloud-congithub
  cloud:
    config:
      server:
        git:
          uri: https://github.com/githubls2002/springcloud.git
          search-paths: config
          username: githubls2002
          password: github43ls
          skipSslValidation: true
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #注册中心的访问地址

  instance:
    prefer-ip-address: true   #是否将当前的服务ip注册到Eureka Server

