#server:
#  port: 8233 #端口
#spring:
#  application:
#    name: cloud-login  #当前服务注册在 Eureka Server 上的名称
#  datasource:
#    url: jdbc:mysql://localhost:3306/ebook?characterEncoding=utf-8&serverTimezone=UTC
#    username: root
#    password: 888888
#    driver-class-name: com.mysql.cj.jdbc.Driver
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/  #注册中心的访问地址
#
#  instance:
#    prefer-ip-address: true   #是否将当前的服务ip注册到Eureka Server
#
